GCP tests
protofire/polkadot-failover-mechanism pull request #15
Opened 2020-10-06 12:31 UTC by trezorg

2020-10-06 18:18 UTC, ArseniiPetrovich commented on tests/gcp/bundle_test.go
> +Add or ensure next rpuoles are presents for google account member that is being used for terraform:
rpuoles => rules

2020-10-06 18:23 UTC, ArseniiPetrovich requested changes
I generally love the PR, but to make it merged we need to enable CI with these tests first. Please, check the following configuration: https://github.com/protofire/polkadot-failover-mechanism/blob/master/.circleci/config.yml , adjust it to include GCP tests, make sure all the tests are passed with the CI and then PR can be safely merged.
P.S. Contact me for any details needed 👍

2020-10-08 07:55 UTC, trezorg commented on tests/gcp/bundle_test.go
> +Add or ensure next rpuoles are presents for google account member that is being used for terraform:
Fixed

2020-10-08 07:59 UTC, trezorg commented
> I generally love the PR, but to make it merged we need to enable CI with these tests first. Please, check the following configuration: https://github.com/protofire/polkadot-failover-mechanism/blob/master/.circleci/config.yml , adjust it to include GCP tests, make sure all the tests are passed with the CI and then PR can be safely merged.
> P.S. Contact me for any details needed

Hi.
https://app.circleci.com/pipelines/github/protofire/polkadot-failover-mechanism/141/workflows/8ec8e0f8-49a0-4286-8039-31cdfbf1e34a

Passed Circle CI tests for gcp-tests branch

2020-10-08 11:20 UTC, ArseniiPetrovich approved these changes
Awesome! LGTM!

2020-10-08 11:23 UTC, merged